version: "3.7"

services:
  postgres:
    image: postgres
    container_name: queries_challenge_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgress
    network_mode: host
volumes:
  pgdata:
    driver: local
